id: A4BF0CC06
title: Fulfilment Offering for Nyangrel Nyima Özer's Treasure Practice of Black Hayagrīva
  with an Iron Sword
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:56.707245
  last_modified_at: 2022-03-01 03:56:56.707248
