id: A4BF0CC06
title: Prayer to the Lineage of the Supreme Hayagrīva Emanation from the Aural Transmission
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:56.710342
  last_modified_at: 2022-03-01 03:56:56.710345
