id: A4BF0CC06
title: Daily Practice of Hayagrīva
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:56.706175
  last_modified_at: 2022-03-01 03:56:56.706178
