id: A4BF0CC06
title: A Sādhana of Hayagrīva’s Assembly, from the Heart-Essence of the Vast Expanse
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:56:56.704791
  last_modified_at: 2022-03-01 03:56:56.704799
